### ISSUE TITLE
panic in combo-operator when applying a combination with one value

### ISSUE THREAD

**Issue by exdx** [operator-framework/combo#79]
Steps to reproduce locally:
Apply template
```
apiVersion: combo.io/v1alpha1
kind: Template
metadata:
  name: cm-template
spec:
  body: |
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cm
      namespace: default
    data:
      key: VALUE
```
Apply combination
```
apiVersion: combo.io/v1alpha1
kind: Combination
metadata:
  name: cm-feature
spec:
  template: cm-template
  arguments:
  - key: VALUE
    values:
    - "fox"
  apply: true
```

This causes a panic locally for the combo operator
```
panic: runtime error: index out of range [-1]

goroutine 199 [running]:
github.com/operator-framework/combo/pkg/combination.(*stream).nextIterativeCombination(0xc0006174a0)
	/Users/dsover/code/src/combo/pkg/combination/combination.go:113 +0x325
github.com/operator-framework/combo/pkg/combination.(*stream).Next(0xc000223c50, {0x0, 0x0})
	/Users/dsover/code/src/combo/pkg/combination/combination.go:212 +0x2e
github.com/operator-framework/combo/pkg/template.(*builder).Build(0xc0006cd980, {0x17ab318, 0xc000223c50})
	/Users/dsover/code/src/combo/pkg/template/builder.go:45 +0x7a
github.com/operator-framework/combo/pkg/controller.(*combinationController).Reconcile(0xc0000ab420, {0x17ab318, 0xc000223c50}, {{{0x0, 0x14b8ca0}, {0xc00041f278, 0xc0006e9f00}}})
	/Users/dsover/code/src/combo/pkg/controller/combo_controller.go:136 +0x478
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00014c3c0, {0x17ab318, 0xc000223bc0}, {{{0x0, 0x14b8ca0}, {0xc00041f278, 0xc0006bb300}}})
	/Users/dsover/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:114 +0x222
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00014c3c0, {0x17ab270, 0xc000301f00}, {0x1457a60, 0xc0006eace0})
	/Users/dsover/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:311 +0x2f2
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00014c3c0, {0x17ab270, 0xc000301f00})
	/Users/dsover/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/Users/dsover/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/Users/dsover/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:223 +0x354
```

However, removing the combination and applying one with more than one argument set causes no issues. 
```
apiVersion: combo.io/v1alpha1
kind: Combination
metadata:
  name: cm-feature
spec:
  template: cm-template
  arguments:
  - key: VALUE
    values:
    - "zookeeper" 
    - "fox"
  apply: true
```

This may be related to the new method of creating combinations iteratively.
